### ISSUE TITLE
현대 IMAZU HNT-3100 Series 현대통신향 월패드 시리얼 제어 코드

### ISSUE THREAD

**Issue by jeongheon81** [zooil/wallpad#1]
[myhyundai_serial_wallpad.zip](https://github.com/zooil/wallpad/files/4846091/myhyundai_serial_wallpad.zip)

거실외 방 3개의 전등, 환풍기, 주방가스차단기, 외출차단기, 난방 모니터링 구현 하였습니다.
난방은 확인만 가능하며 온도는 1도 단위만 가능합니다.

추가 사항으로 MQTT Discovery를 이용하여 구성요소가 자동으로 등록 되게 하였습니다.
그리고 가끔 월패드에서 발송하는 상태 요청이 중지되어, 이를 모니터링 하여 대신 상태 요청을 하도록 하였습니다.
대신 상태 요청을 몇번하면 월패드 요청이 다시 살아 납니다. 그래서 살아난게 감지 되면 대신요청은 중지 됩니다.
대신요청이 장기간 지속되면 월패드 상태를 끊김으로 표시하는 바이너리 센서를 추가 하였습니다.

**Comment by zooil** [comment]
네 현대통신용으로 추가해두겠습니다. 기존것을 바꾸어도 될까요? 사실 제가 js 코드를 만든게 아니고 여기저기서 가져다가 올려둔 것이라서...
바꿔도 문제 없을 것 같다면 현대통신 시리얼 기본 코드로 교체해둘까 합니다.

**Comment by zooil** [comment]
기본 hyundai_serial.js 로 반영해두었습니다.
